language: bash
install:
  - sudo apt-get install bc
script:
  - bash addr2geo.sh \\xE5\\xB9\\xBF\\xE5\\xB7\\x9E\\xE5\\xA1\\x94
  - bash addr2point.sh \\xE5\\xB9\\xBF\\xE5\\xB7\\x9E\\xE5\\xA1\\x94
  - bash geo2point.sh ".=UOqMLBsMwqPA;"
  - bash point2coord.sh 12616098.76, 2628657.08
  - bash coord2point.sh 113.331110, 23.112097
  - bash point2addr.sh 12616098.76, 2628657.08
  - bash gmaps2bdmaps.sh 23.10641, 113.32449
